version: ~> 1.0

dist: xenial
group: edge
virt: lxd

language: c

arch:
  - amd64
  - arm64
  - arm64-graviton2
#  - ppc64le
#  - s390x

cache: ccache

os:
  - linux
#  - osx

env:
  global:
    - MAKEFLAGS="-j 2"

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libtool
    - libxml2-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install ccache; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - git submodule update --init

install:
  - autoreconf -f -i
  - mkdir build
  - cd build
  - ../configure CFLAGS="-Wall -W -Werror -g"
  - make

script:
  - make check
